# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_auto_20161223_0323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trading_Date',
        ),
    ]
