# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cron_Job_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=48, verbose_name='cron_job_title')),
                ('exec_time', models.DateTimeField(auto_now_add=True, verbose_name='cron_job_exec_time')),
                ('status_code', models.CharField(choices=[('1', 'cron_job_success'), ('2', 'cron_job_failed')], default='1', max_length=1, verbose_name='cron_job_status')),
                ('error_message', models.CharField(default='', max_length=120, verbose_name='cron_job_error_message')),
            ],
        ),
        migrations.CreateModel(
            name='Trading_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField(unique=True, verbose_name='trading_date')),
                ('day_of_week', models.PositiveIntegerField(default=9, verbose_name='day_of_week')),
                ('is_future_delivery_day', models.BooleanField(default=False, verbose_name='is_future_delivery_day')),
                ('first_trading_day_of_month', models.BooleanField(default=False, verbose_name='first_trading_day_of_month')),
                ('last_trading_day_of_month', models.BooleanField(default=False, verbose_name='last_trading_day_of_month')),
                ('is_market_closed', models.BooleanField(default=False, verbose_name='is_market_closed')),
            ],
        ),
        migrations.CreateModel(
            name='Twse_Index_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField(unique=True, verbose_name='trading_date')),
                ('trade_volume', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='trade_volume')),
                ('trade_transaction', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='trade_transaction')),
                ('trade_value', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='trade_value')),
                ('opening_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='opening_price')),
                ('highest_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='highest_price')),
                ('lowest_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='lowest_price')),
                ('closing_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='closing_price')),
                ('price_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price_change')),
                ('week_avg', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='week_avg')),
                ('two_week_avg', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='two_week_avg')),
                ('month_avg', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='month_avg')),
                ('quarter_avg', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='quarter_avg')),
                ('half_avg', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='half_avg')),
                ('year_avg', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='year_avg')),
                ('day_k', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='day_k')),
                ('day_d', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='day_d')),
                ('week_k', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='week_k')),
                ('week_d', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='week_d')),
                ('month_k', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='month_k')),
                ('month_d', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='month_d')),
                ('year_value_avg', models.DecimalField(decimal_places=0, max_digits=15, null=True, verbose_name='year_value_avg')),
            ],
        ),
    ]
