# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField(unique=True, verbose_name='trading_date')),
                ('serial_id', models.PositiveIntegerField(unique=True, verbose_name='serial_id')),
            ],
        ),
        migrations.RunSQL("INSERT INTO sgx_download_log (trading_date, serial_id) VALUES ('2016_12_22', 3740)"),
    ]
